# Change these first
owner: [Tên-GitHub-Của-Bạn] # Thay bằng Username GitHub của bạn (ví dụ: truonghoc)
repo: [Tên-Repository-Của-Bạn] # Thay bằng tên Repo bạn vừa tạo (ví dụ: website-monitor)

sites:
  - name: ParadiseHRM NAVT
    url: https://navt.paradisehrm.com

status-website:
  # Nếu bạn không có tên miền riêng (domain), hãy để dấu # trước cname như dưới đây
  # cname: demo.upptime.js.org
  
  # Bỏ dấu # ở dòng baseUrl và điền /tên-repo của bạn vào để trang web hoạt động
  baseUrl: /[Tên-Repository-Của-Bạn] 
  
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ParadiseHRM Status
  introTitle: "**Hệ thống theo dõi trạng thái ParadiseHRM**"
  introMessage: Trang web này theo dõi thời gian hoạt động (uptime) của hệ thống ParadiseHRM hoàn toàn tự động.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Cấu hình kiểm tra mỗi 5 phút một lần
workflow-schedule:
  uptime: "*/5 * * * *"
