owner: 2351010236-droid
repo: website-monitor

sites:
  - name: ParadiseHRM NAVT
    url: https://navt.paradisehrm.com

status-website:
  # Điền tên miền của bạn vào đây
  cname: serverless.thithiencorp.dpdns.org
  # Khi dùng tên miền riêng, baseUrl PHẢI là dấu gạch chéo
  baseUrl: /
  name: ParadiseHRM Status
  introTitle: "**Hệ thống giám sát ParadiseHRM**"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  navbar:
    - title: Status
      href: /
